# Generated by Django 5.2.3 on 2025-09-04 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVaraity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('PL', 'PLAIN'), ('GI', 'GINGER'), ('ML', 'MASALA'), ('GR', 'GREEN'), ('KL', 'KIWI')], max_length=2)),
            ],
        ),
    ]
