# Generated by Django 5.2.3 on 2025-09-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivaraity',
            name='description',
            field=models.TextField(default='No description', max_length=500),
        ),
        migrations.AddField(
            model_name='chaivaraity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chaivaraity',
            name='type',
            field=models.CharField(choices=[('PL', 'PLAIN'), ('GI', 'GINGER'), ('ML', 'MASALA'), ('GR', 'GREEN'), ('KL', 'KIWI'), ('LE', 'LEMON')], max_length=2),
        ),
    ]
