# Generated by Django 6.0 on 2025-12-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivarity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
