# Generated by Django 6.0 on 2025-12-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaivarity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivarity',
            name='tea_type',
            field=models.CharField(choices=[('MLT', 'MASALA TEA'), ('GRT', 'GINGER TEA'), ('KLT', 'KIWI TEA'), ('ELT', 'ELACHI TEA'), ('GT', 'GREEN TEA'), ('BLT', 'BLACK TEA'), ('HET', 'HERBAL TEA'), ('MLT', 'MILK TEA')], max_length=5),
        ),
    ]
